title: Nicholas Lindsay
description: Nicholas Lindsay's website
theme: null # important: disable builtin theme

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

include:
  - _pages

markdown: kramdown
